### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#1452]
This issue is for organizing the work that needs to happen before we release 1.0.0.

**Any issue/PR that should be closed in order to ship 1.0 should be [added to the 1.0.0 milestone](https://github.com/rackt/react-router/milestones/1.0.0). This issue is only for consolidating tasks, which may actually be discussed in multiple PRs and/or issues.**

#### Code

- [ ] Add a reliable `canGo(n)` implementation to all histories. This includes adding the `current` history index to all histories (see #843 and #1376 for further discussion)
- [ ] Make "leave" transition hooks work only on components that are leaving the screen (see #1328)
- [ ] Don't call any "enter" hooks until after we've resolved all redirects (see #1356). This means we can't use the "enter" hook to implement redirects. Instead, it needs to be built-in to the route resolution algorithm
- [x] Fix the failing scroll management test (see #1449)
- [ ] Fix the `isActive` implementation and get some more stringent tests around it (see #1441)
- [ ] Provide decorators for folks using ES6 classes (don't want to use mixins, see #1173, #1433)

#### Docs

- [ ] Fill in the path-matching guide (see #1451)
- [ ] Remove `#TODO` links in the documentation (see e.g. #1417)
- [ ] Upgrade guide (see #1408)

I'm sure there are quite a few issues I've missed. Please restrict comments to discussing stuff that needs to be added to the list and/or assigning work. I'll keep this list up to date as we get closer.

**Comment by SpainTrain** [comment]
It seems like addressing prop passing to children (as discussed in https://github.com/rackt/react-router/issues/1531) would be relevant before a final release.  I'm not clever enough to think of a more elegant solution, so I won't assert that one ought to be developed, but I think a compelling "company-line" rational for why it isn't supported would be super helpful to folks (whether they are upgrading or using react-router for the first time).

(If this comment is more appropriately placed in https://github.com/rackt/react-router/issues/1531 I am happy to move it)

**Comment by ryanflorence** [comment]
yeah yeah yeah, we're doing it.

**Comment by knowbody** [comment]
yippie! :tada:

**Comment by SpainTrain** [comment]
I have certainly been impressed with and appreciated the responsiveness and support (and patience) the maintainers have provided during the beta!

much :heart: all
