### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#2646]
This might not be the best way to manage this (one gigantic issue), but @mjackson and I are a solid 50% done with all of this anyway, so I'm not too concerned.

@taion you'll likely have some questions since this affects a lot of what you're trying to do, please chat me up on discord before we clog up this issue with back-and-forth conversation :)

Router 2.0 Roadmap
==================

TOC

- [Motivations](#motivations)
- [x] [Ship History 2.0](#ship-history)
- [x] [Refactor `useRoutes`](#use-routes)
- [x] [Export only `router`](#context-router)
- [x] [Add Router `render` prop](#render-prop)

<a id="motivations"></a>

Motivations for the following API changes are all about cleaning up and clarifying the coupling between React Router and History; this generally translates to "You won't need to know anything about History anymore."

- Learning the router is complicated by History, you have to learn both APIs and the line between them is unclear. This affects end users trying to use the libraries together as well as contributors (for example duplication of docs is also a problem).

- We have some rough edges around ingration with libraries like React native, Redux, Relay, and our own AsyncProps.

- React 15 is only going to allow components to export only one object to "context" (we only want one anyway)

The following issues should help address these concerns.

**Note about upgrading**

All v1.0.0 APIs will continue to work in v2.0.0. An app using only public API should be able to drop in v2.0.0 and just get warnings. Old API will be removed in 3.0.0. If you update your code and no longer get warnings, you should be able to upgrade to 3.0 w/o trouble.

<a id="ship-history"></a>

Ship History 2.0
----------------

It's really just removing deprecated API. The rest of these items all kind of depend on it though.

<a id="use-routes"></a>

Refactor route matching out of `useRoutes` and into `match`
-----------------------------------------------------------

### Background

Currently we wrap a history with `useRoutes` so it is now aware of routes and performs the match against them. This changes the signature and timing of `listen` (making it async) causing difficulty when integrating or using alongside libraries like redux and react native.

Additionally, navigating outside of components (like in flux and redux) is complicated by `Router` wrapping the history provided as a prop.

### Goals

- Remove need for `listenRoutes` to integrate with other libs
- Make navigating outside of components simpler for redux/flux etc.
- Not require apps to wrap their singleton history in things like
  `useQueries` in order to navigate outside of components
- apps can still learn about History and add behavior if they choose,
  (custom queryString parsing, etc.) and `Router` should not touch the
  history provided

### Upgrading

```js
////////////////////////////////////////////////////////////////////////////////
// Rendering
// v1.0.0
import createBrowserHistory from 'history/lib/createBrowserHistory'
render(<Router history={createBrowserHistory()}/>, el)

// v2.0.0
import { browserHistory } from 'react-router'
render(<Router history={browserHistory}/>, el)

////////////////////////////////////////////////////////////////////////////////
// Navigating outside of components

// v1.0.0
// probably exported from a module somehwere like this
import createBrowserHistory from 'history/lib/createBrowserHistory'
import useQueries from 'history/lib/useQueries'
const createHistory = useQueries(createBrowserHistory)
export default createHistory()
// and then used in an action or somehwere
import appHistory from './appHistory'
appHistory.push(...)

// v2.0.0
// React Router exports a singleton
import { browserHistory } from 'react-router'
browserHistory.push(...)
```

### Tasks

While the nitty gritty won't be this simple, this is what will probably need to happen:

- remove `useRoutes` and move all route matching to `match`
- use `match` inside of `Router` instead of wrapping the history provided in anything (don't alter history)
- create `hashHistory` and `browserHistory` singletons, exported from `index.js`
- remove default to `hashHistory` and require devs to provide one, should help with people not understanding that there's a better option, and allow devs to decrease the bundle size of their app

<a id="context-router"></a>

Export only `router` to context
-------------------------------

### Background

Right now we put `history`, `location`, and `route` (sometimes) on context, we also pass a bag of props to route components. Turns out there's some overlap between them. We're tempted to add more to context, and add more to props because the line and purpose between them isn't clear.

React Router continues to strive to be just one library in a wonderful ecosystem of other libraries, prescribing strategies for data flow in an app is not our goal. We will put only what we absolutely need in context (which can be summed up with "what does `Link` need?).  Everything else will go to route components as props.  The opinions of the app can take over from there.

Context was recently documented, so we no longer need the mixins to hide the context API. It's up to the app to decide if it wants to use context directly or continue to hide it with mixins or higher order components.

Also, react 15 or 16 will only allow one `contextType`. We've been talking about only have one context type for a while. Now is the time.

Finally, in the global effort to make History an implementation detail, we need to provide something else to navigate around in components.

### Goals

- Make separation between what is on context v. route props clear, and remove overlap
- Let apps decide how to get props the router gives them down the render tree
- Remove need to learn History API

### Tasks

- Deprecate all items on context: `history`, `location`, `route`
- Add `context.router` that looks like this:

    ```js
    router: shape({
      push: func,
      replace: func,
      isActive: func,
      addRouteLeaveHook: func
    })
    ```
- Pass `router` as a prop to route components
- Deprecate all mixins
- Deprecate passing `history` to route components
- proxy push/replace/isActive/addRouteLeaveHook to underlying history (so integration with a custom `history` will work)
- automatically remove route leave hooks since we should know everything we need to know, so devs don't have to and there's no reason to leave them hanging around.

### Upgrading

<a id="history-methods"></a>

#### History methods

In all cases where you once had a `history` for navigation, you now have a `router` with different methods.

```js
// v1.0.0
history.pushState(state, path, query)
history.replaceState(state, path, query)

// v2.0.0
router.push(path)
router.push({ path, query, state }) // new "location descriptor"

router.replace(path)
router.replace({ path, query, state }) // new "location descriptor"
```

#### Navigating in route components

```js
// v1.0.0
class RouteComponent extends React.Component {
  someHandler() {
    this.props.history.pushState(...)
  }
}

// v2.0.0
class RouteComponent extends React.Component {
  someHandler() {
    this.props.router.push(...)
  }
}
```

#### Navigating inside deeply nested components

```js
// v1.0.0
const DeepComponent = React.createClass({
  mixins: [ History ],

  someHandler() {
    this.history.pushState(...)
  }
}

// v2.0.0
// You have a couple options:
// Use context directly (recommended)
const DeepComponent = React.createClass({
  contextTypes: {
    router: object.isRequired
  },

  someHandler() {
    this.context.router.push(...)
  }
}

// create your own mixin:
const RouterMixin = {
  contextTypes: {
    router: object.isRequired
  },
  componentWillMount() {
    this.router = this.context.router
  }
}

const DeepComponent = React.createClass({
  mixins: [ RouterMixin ],
  someHandler() {
    this.history.pushState(...)
  }
}

// use the singleton history you are using when the router was rendered,
import { browserHistory } from 'react-router'

const DeepComponent = React.createClass({
  someHandler() {
    browserHistory.push(...)
  }
}
```

#### Lifecycle Mixin with route components

```js
// v1.0.0
const RouteComponent = React.createClass({
  mixins: [ Lifecycle ],
  routerWillLeave() {
    // ...
  }
})

// v2.0.0
const RouteComponent = React.createClass({
  componentDidMount() {
    const { router, route } = this.props
    router.addRouteLeaveHook(route, this.routerWillLeave)
  }
})

// or make your own mixin, check it out in the next section
```

#### Lifecycle Mixin with deep, non-route components

```js
// v1.0.0
const DeepComponent = React.createClass({
  mixins: [ Lifecycle ],
  routerWillLeave() {
    // do stuff
  }
})

// v2.0.0
// you have a couple of options
// first you can put the route on context in the route component
const RouteComponent = React.createClass({
  childContextTypes: {
    route: object
  },

  getChildContext() {
    return { route: this.props.route }
  }
})

// and then access it on your deep component
const DeepComponent = React.createClass({
  contextTypes: {
    route: object.isRequired,
    router: objec.isRequired
  },

  componentDidMount() {
    const { router, route } = this.context
    router.addRouteLeaveHook(route, this.routerWillLeave)
  }
})

// or make your own mixin that will work for both route components and
// deep components alike (as long as your route component puts `route`
// on context
const Lifecycle = {
  contextTypes: {
    route: object.isRequired,
    router: objec.isRequired
  },

  componentDidMount() {
    const router = this.context.router
    const route = this.props.route || this.context.route
    router.addRouteLeaveHook(route, this.routerWillLeave)
  }
}
```

<a id="render-prop"></a>

Add `render` prop to `Router`, remove `RoutingContext` prop
-----------------------------------------------------------

### Background

The functional composition of `history` is awesome, but we also need this kind of composition for React Router when it's time to render. While we can add some behavior into `history` we lack the necessary lifecycle hooks that components give us. Integrations also need all of the routing information in aggregate (like all the components and routes).

Our current workaround is the `RoutingContext` prop, but that only lets us add one level of behavior.  Consider an app that was built with Async Props, but now wants to iterate to using Relay, as well as add a new scroll restoring behavior. If each of these components used the `RoutingContext` prop API, they would all render a `RoutingContext` and therefore can't be used together.

### Goals

- Allow integration for middleware components that need lifecycle hooks and the aggregate routing information
- Allow multiple levels of behavior, not just one

### Upgrading

```js
// v1.0.0
render(<Router RoutingContext={AsyncProps}/>, el)

// v2.0.0
render((
  <Router render={(props) => (
    <AsyncProps {...props} render={(props) => (
      <RoutingContext {...props} />
    )}/>
  )}/>
), el)

// While that's more code, now we can do this:
render((
  <Router render={(props) => (
    <AsyncProps {...props} render={(props) => (
      <RelayRoutes {...props} render={(props) => (
        <ScrollRestorer {...props} render={(props) => (
          <RoutingContext {...props} />
        )}/>
      )}/>
    )}/>
  )}/>
), el)
```

### Tasks

- Remove `RoutingContext` prop, no need for deprecation warnings, it's undocumented and everybody we've told to try it got an earful of "we aren't sure about this thing yet"
- Add `render` prop to `Router`
- Add a default prop that just renders a `RoutingContext`
- Write a document about how to write a middleware component (should continue to send down the `props` in a method called `render`

---

Holy smokes that looks like a lot, it's really not too much, and we're feeling really good about it all.

**Comment by timdorr** [comment]
Do you guys have some code to push so we can see where you're at and where we can help? You have the advantage of being in person, so your cycle times are much lower, but d be happy to help with any menial changes that need to be made.

**Comment by ryanflorence** [comment]
I don't think @mjackson has internet on his flight home from London, I'll probably have some code to push by the end of my flight. And then others can poke the code and see if it works as we'd like it to.

**Comment by timdorr** [comment]
Just some thoughts/feedback now that I've had a chance to read through all of this:

> Remove default to hashHistory and require devs to provide one, should help with people not understanding that there's a better option, and allow devs to decrease the bundle size of their app

I think, for the sake of making the upgrade less painful for hash users, we should leave it in the repo, but not export it. Users that need it still have a one-liner to access it, but we also don't increase bundle size. It can be explicitly deprecated for removal in a 2.x release.

> Add context.router that looks like this:

Could we add `history` as another context object property? I know we can get access to it via the singleton export, but that is convention over configuration. I'm pretty ambivalent about it, though. The only things I can think of needing access to history's API can be accomplished in other ways, so this may be a moot point.

> `const RouterMixin = {`

Given how simple this is, I think we should bundle it into the library. Then I can throw `@router` at the top of my components to decorate in `this.router` really easily. 

> ```js
render((
  <Router render={(props) => (
    <AsyncProps {...props} render={(props) => (
      <RelayRoutes {...props} render={(props) => (
        <ScrollRestorer {...props} render={(props) => (
          <RoutingContext {...props} />
        )}/>
      )}/>
    )}/>
  )}/>
), el)```

I think that will actually end up looking like this (provide with a good `compose` implementation):

```js
render((
  <Router render={compose(
    renderAsyncProps,
    renderRelayRoutes,
    renderScrollRestorer,
  )}>
), el)
```

You can just bump up the order of the `render` function and make it easy for them to be nested. This is up to the library to implement, so I would document it as such to establish the pattern and make it the norm for other libraries. Though it is hard to enforce...

Overall, this looks great. There's a trend towards increasing userland code with this route, but I don't think it's all that terrible and really only affects those doing more eccentric things with the router.

**Comment by taion** [comment]
:100: on this, this is fantastic. Have a few minor comments/notes but will write them up later.

**Comment by ryanflorence** [comment]
> I think, for the sake of making the upgrade less painful

1.0.0 API will work in 1.1.0, so upgrading should be "drop-in but now you have warnings". So yeah, we'll still have a default but with a warning.

**Comment by ryanflorence** [comment]
@timdorr 

> Could we add history as another context object property?

Nope, React 15 or 16 won't let us, reread the issue :P Also, history is not going to be router API anymore. If you need your history, your app will have the object it passed to router, just import it and use it wherever, you don't need it in the render tree.

**Comment by ryanflorence** [comment]
@timdorr 

> Given how simple this is, I think we should bundle it into the library.

Another great reason *not* to have it in the package :P We've never wanted to be in the "mixins v. decorators" business and now that context is documented we don't have to be.

**Comment by timdorr** [comment]
I meant having history as a property next to push and replace and all that jazz. But you're right, hence my ambivalence :smile:

**Comment by ryanflorence** [comment]
> Though it is hard to enforce

I would personally do the component version not the compose version, and since the compose version can be built on top of the component version, we'd keep with our philosophy of "building the lower-level thing and letting apps get opinionated about [stuff]"

**Comment by ryanflorence** [comment]
@timdorr 

> Overall, this looks great. There's a trend towards increasing userland code with this route, but I don't think it's all that terrible and really only affects those doing more eccentric things with the router.

:D :dancer: That's exactly the goal, thanks for considering all of this. We'll do our best to get some code up for everybody to help us fix soon.

**Comment by bjrmatos** [comment]
Any love for #2186 in v1.1.0? :)

**Comment by timdorr** [comment]
@bjrmatos There's some support work on history for that first. Then it can be implemented on router. But it's independent of the changes here.

**Comment by ryanflorence** [comment]
@bjrmatos @timdorr I believe that's [here](#history-methods) isn't it?

**Comment by taion** [comment]
Okay, got back to my computer. Some more detailed thoughts:

- I really like the idea of exporting history singletons in the router library. This gives us a principled way to "hide" `history` as a dependency for most users, while not doing the weird-seeming thing of just re-exporting all `history` methods that we rejected in https://github.com/rackt/react-router/issues/2211. We should figure out the default `queryKey` setting or equivalent for `hashHistory`, though - maybe resolve https://github.com/rackt/history/issues/163 first.

- The `context.router` API looks fantastic and is a great simplification. I'm not a huge fan of the current `context.location` and won't be sad to see it go. I also like explicitly hiding the `listen` method, since now that you're in a React context, you can just receive props.

- We noted that the `Lifecycle` example doesn't have the `componentWillUnmount` hooks, but that just brings up the point that they're not really necessary - we can just tear down "route leave" hooks when we leave the route, which is actually good enough for most use cases IMO.

- I think `props.render` is a better API than the current `props.RoutingContext`. Relay root renderers are configured the same way, and it's a good, versatile pattern. My personal preference for userspace composition looks like https://github.com/rackt/react-router/blob/v1.0.0/modules/__tests__/Router-test.js#L286-L292. In this context it'd be something like:

```js
<Router render={props => (
  <RelayWrapper {...props} />
    <SomeOtherWrapper {...props} />
      <RoutingContext {...props} />
    </SomeOtherWrapper>
  </RelayWrapper>
)} />
```

But as noted, this is all in userspace anyway, so users can do whatever they want.

Overall, I'm 100% behind this. This is really fantastic, @ryanflorence.

**Comment by timdorr** [comment]
@ryanflorence Yes, but this is about moving that API, not necessarily changing its signature. We can certainly do it at the same time, but it's not a requirement for this issue to close.

**Comment by timdorr** [comment]
@taion I like that form of render even more! I was in FP mode in my head, so I forgot about props.children. That reads a lot better without having to layer on additional functional concepts.

**Comment by taion** [comment]
@timdorr 

Yeah, the main thing is that "what users choose to do" shouldn't affect our choice of API here - we don't have any control over the patterns they use.

For me, I'm probably going to keep just exposing `<RelayRouter>` as my main entry point (since most people won't need to compose multiple "routing context wrappers"), so not even the users of `react-router-relay` will see any overt difference.

**Comment by taion** [comment]
@ryanflorence 

On terminology - for the pushable locations, do you like the term "location descriptor"? I have it written up as "location spec" in my in-progress docs for the corresponding changes on `history` on https://github.com/rackt/history/pull/168, but I don't really like the "location spec" term.

**Comment by timdorr** [comment]
@taion The only gotcha is we can't enforce using children, so that kind of composition can break down if a render wrapper doesn't expect them. We should document whatever form we choose so that the pattern and use cases for it are known.

**Comment by timdorr** [comment]
What about just calling it a capital L "Location"?

**Comment by ryanflorence** [comment]
The term "location spec" makes me think of testing. Like its a "location test" and I'm like "wha?"

Capital L location makes me thing about classes, instances, namespaces, structs, etc.

I like "location descriptor" because the object "describes something that looks like a location" like the old term "React descriptor" before they switched it to "React Element".

That's my loosely held preference. I'm happy to go with the flow if somebody else has a strong opinion.

**Comment by taion** [comment]
I like "location descriptor" more than "location spec". Will update my PR to history when I get a chance.

**Comment by ryanflorence** [comment]
:shipit:

**Comment by mjackson** [comment]
Just touched down and got internet. I've got a few things to push. I'll
start a PR and we can go from there.

**Comment by knowbody** [comment]
this is going to be beautiful :art:

**Comment by mjackson** [comment]
Update: Just shipped history v1.14.0 with the `push`/`replace` API we need here. v2 should follow shortly, but it'll just remove a bunch of deprecated API.

**Comment by timdorr** [comment]
FYI, history v1.14.0 breaks some tests around Link and isActive. I'm looking into updating the internal usage of our APIs relating to this change. I'm mainly waiting on the refactor around `useRoutes`, so I'll push after that's in place.

**Comment by timdorr** [comment]
![dpayld](https://cloud.githubusercontent.com/assets/17882/11634394/2a260732-9cde-11e5-8b61-8908b32969d2.jpg)

Once #2659 lands and thanks to #2660.

**Comment by taion** [comment]
Are we all okay with making this actually be 1.2.0? The Router-internal API changes here are orthogonal to the changes in the `history` APIs, so I don't think we'd meaningfully inconvenience our users by cutting a 1.1.0 that only adjusts to match the new `history` API.

**Comment by timdorr** [comment]
Yeah, that's what needs to happen now. We'll have to cherry pick off #2647, #2649, and #2651 and possibly some other commits into a 1.2 branch (or create a 1.1 branch; either or). We should do that ASAP before things get out of hand :smile:

**Comment by timdorr** [comment]
s/v1.1/v1.2/

@mjackson or @ryanflorence Can we get 1.1 shipped as an interim release to 1.2? We're getting a ton of questions about the deprecation warnings from `history` 1.14 and 1.15.

**Comment by timdorr** [comment]
Note: I've pushed up a [`1.1.x` branch](https://github.com/rackt/react-router/tree/1.1.x) that should have everything needed for a 1.1 release. We may want to wait on #2676 (or whatever it turns into) to ship, since `createLocation` is going to go away.

**Comment by timdorr** [comment]
Just talked with @ryanflorence about this. He's going to cut a 1.0.2 release to lock `history` at 1.13.1 and stop the deprecation warnings. We'll do all the history and router API changes all together in the 1.1 release as originally planned, which will keep the number of upgrade paths to a minimum. Less API churn == better dev experience.

**Comment by ryanflorence** [comment]
1.0.2 is out

**Comment by timdorr** [comment]
Thanks, @ryanflorence! 

Of note, we now have [a 1.0.x branch](https://github.com/rackt/react-router/tree/1.0.x).

**Comment by ryanflorence** [comment]
may it rest in peace.

**Comment by silvenon** [comment]
Maybe I'm missing something obvious, but why isn't this the recommended way of acquiring the history object?

```js
import { browserHistory } from 'react-router'
```

As far as I understand, this will work in every case, outside of components or inside.

**Comment by taion** [comment]
That is what's in the roadmap above.

It will work for most cases, but it won't work if you have to configure the history object while creating it.

**Comment by silvenon** [comment]
Oh, right. Thanks.

**Comment by taion** [comment]
Oops I missed something - why are we calling this v2 instead of v1.1 now?

**Comment by taion** [comment]
Ah, okay, I see your Gist @ryanflorence. Do you want me to leave comments there?

**Comment by ryanflorence** [comment]
Sure, but I if you are opposed, we're pretty set on it given everything that just happened with history's versions :P

**Comment by taion** [comment]
Ahh I'll just do it here. I was actually previously a big proponent of considering deprecation warnings as "breaking", but I've since changed my mind and I think on balance for good reasons.

@zpao's React meeting notes give a good summary of why the upstream React post-1.0.0 plans involve deprecating on minor release and removing API points on major releases: https://gist.github.com/zpao/6e12ee0f46ce87af2287#versioning. Concrete reasons aside, there's a lot of value to just being consistent, as opposed to adopting an idiosyncratic versioning strategy.

I'm well aware that the `history` upgrades have been painful to a segment of our user base, but I think we're mis-diagnosing the pain. I think the problem isn't that there were deprecation warnings - in general those are things that you have to expect when you're only pinning a major version.

The issue was rather that these were deprecation warnings that users couldn't do anything about because they were from how the Router used `history`, i.e. that they were just using `<Link>` but getting warned about `history.pushState` which they never explicitly invoked. Normally we'd have just updated the router to use the new `history` APIs and not transitively emit deprecation warnings, but the pending API changes made it not make sense to schedule such a change.

In general then I think deprecating on minor versions is probably the best way to approach these sorts of things, as long as we can update React Router within a few days of making deprecations on `history`. It's going to be most consistent with other packages and with upstream especially, and it's going to make that major version number mean the most.

**Comment by taion** [comment]
Summary: The npm trolling was because users didn't have a way to fix those warnings because we didn't update the Router, and our attempt to pin the old version led to npm peer dependency hell. This won't matter once we make `history` a regular dependency; anyway we should always try to update Router for new deprecations within a few days anyway.

**Comment by timdorr** [comment]
It's simply that we released a new API *and* added deprecations **at the same time**. There was no upgrade period at all. We should do a tick-tock release cycle at the very least, where we implement a new API with one version and deprecate old APIs with the next. Those can be within the same major release, or not.

I don't think we need to follow React's lead on this. They have a more coordinated release schedule and different use cases for their modules. As long as we separate out the API introduction and deprecation warnings, we should be fine.

**Comment by taion** [comment]
Nah, it's totally normal to release new feature plus depreciations. Otherwise you're in a bad place with implicit soft depreciations. 

The problem was really just not updating the router. If we had a version that users could upgrade to without hitting peer dependency hell, it would have been fine.

**Comment by ryanflorence** [comment]
@taion I didn't put it in the medium post but our plan is basically "do what react does", while react is 0.x then they have deprecated in x+1 releases, removed in x+2.

Looking at that gist they are going to make a bunch of people upset, but I agree that would be my preference too, so I guess we still aren't done deciding :P

**Comment by taion** [comment]
@ryanflorence 

I don't think it will make people too upset - when you are on >1 and don't pin your minor version, IMO deprecation warnings are expected, and that's exactly why I have some of my builds fail on warn.

Our problem is a lot simpler. Something like https://github.com/rackt/react-router/issues/2695 is representative - I'm happy to get deprecation warnings because of API deprecations, but in this case we stuck users with deprecations that they couldn't fix!

As a user of React Router, there's absolutely no reasonable way for me to fix those deprecation warnings in my own code.

The 1.0.2 release _should_ have fixed things, except peer dependencies are awful and ended up just breaking npm. Once we move history to a regular dependency with the next API change, we'll be in a spot where we can just downgrade our history dep with an upgrade if we need to. And the steps to fix it weren't just "upgrade React Router", they were "upgrade React Router then mess with your installed packages to fix peer dependency awfulness".

**Comment by ryanflorence** [comment]
> in this case we stuck users with deprecations that they couldn't fix!

Yeah, that was the bigger problem.

**Comment by taion** [comment]
And then the second-biggest problem was that because we did this via a downgrade on a peer dep, npm did awful things to everyone.

If `history` were a normal dep (like it will be), or if it were an upgrade to 1.16, actually everything would have just worked. Sadly, we were in that one corner of the quadrant that broke npm.

**Comment by ryanflorence** [comment]
There are still folks who think that 1.x -> 1.x+1 logging a deprecation warning is a breaking API.

A) React's minor is effectively a major version right now (and npm `^` treats it that way, too). They:

1. Deprecate and warn on x+1
2. Remove deprecated API in x+2

So we figured we'd do what React is "effectively" doing right now.

B) But their proposed changes in that gist are different:

1. Deprecate and warn on 1.x+1
2. Remove deprecated API in 1.x+2

Again, we just want to follow suit with React. Which would make folks with builds that fail on console warnings want something different than the default `^` in package.json

Like you, and React when it starts using major version numbers, my preference is 2, also. If people want their builds to fail on warnings, that is an application decision that requires more effort on the maintainers of that app, not us.

**Comment by taion** [comment]
More than that - I actively _want_ my build to fail when APIs get deprecated by minor version bumps. I have that check in place specifically to stop using APIs that do get deprecated!

Like... maybe I don't have time and then I pin the previous minor version, but "my CI goes red because I'm using deprecated (but still working) APIs" is what I want.

**Comment by taion** [comment]
I might take a stab at `match` over this weekend - just got past some deadlines and whatever. Was the thought just to move out the logic in `useRoutes` to not be a history enhancer?

**Comment by ryanflorence** [comment]
I'm looking for you on discord @taion

**Comment by timdorr** [comment]
I believe the general gist is to move [these lines](https://github.com/rackt/react-router/blob/master/modules/Router.js#L58-L64) out into a singleton module for browser and hash histories. And probably memory too.

**Comment by timdorr** [comment]
Synced up with @taion. Plans sound awesome. I'll let you guys take care of it and will jump on the PR when it's ready so we can merge it quickly :smile:

**Comment by gaearon** [comment]
Let's be careful about encouraging this:

```js
// and then access it on your deep component
const DeepComponent = React.createClass({
  contextTypes: {
    route: object.isRequired,
    router: objec.isRequired
  },
```

as this is exactly the case that might break in future React versions.

**Comment by timdorr** [comment]
Since we're now actually using `history` directly and no longer expecting users to touch it at all, should we move `history` to be a regular dependency? That will certainly solve some issues with NPM error messages as we move forward. It's also a better semantic representation of our relationship to `history`. We're going to have to bundle it for the UMD build anyways.

**Comment by taion** [comment]
For v1.1.x, definitely, yes.

**Comment by ryanflorence** [comment]
@gaeron right, v+2 will only put one thing on context, and the route only goes as far as a prop on the route component, up to apps to get it deeper

**Comment by ryanflorence** [comment]
@gaearon ^

(Sorry, on a phone and mobile has no edit!)

**Comment by timdorr** [comment]
`history` should be ready for v2 with rackt/history#182. Let's do this! :godmode:

**Comment by quicksnap** [comment]
Sorry if this is non-productive but..

.. thank you so much for the work on this! v2 looks really damn awesome! Excited for it! :fireworks: :shipit: :rocket: :guitar:

**Comment by VinSpee** [comment]
Great work on the upgrade. Question about a deprecation:

doing this: `https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#no-default-history` results in a "Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://bit.ly/1mj4IZr". Is this a catch 22? How can I resolve it and use hash history?

**Comment by timdorr** [comment]
@vinspee That is likely coming from React Dev Tools in your browser. If you disable them temporarily, it will go away. You can ignore that error if that's the case.

**Comment by VinSpee** [comment]
@timdorr building without the devtools yields the same result (using a `__DEV__` conditional / webpack flag to render like so:

```
import React, {
  Component,
  PropTypes,
} from 'react';
import { Provider } from 'react-redux';
import { Router, hashHistory } from 'react-router';

export default class Root extends Component {
  static propTypes = {
    routes: PropTypes.element.isRequired,
    store: PropTypes.object.isRequired,
  }

  get content() {
    return (
      <Router history={hashHistory}>
        {this.props.routes}
      </Router>
    );
  }

  get devTools() {
    if (__DEV__) {
      const DevTools = require('./DevTools');
      return <DevTools />;
    }
  }

  render() {
    return (
      <Provider store={this.props.store}>
        <div className="qz-App">
          {this.content}
          {this.devTools}
        </div>
      </Provider>
    );
  }
}
```

**Comment by timdorr** [comment]
I mean the React Dev Tools in Chrome.

**Comment by VinSpee** [comment]
@timdorr ahh my bad! Thanks!

**Comment by EmperorEarth** [comment]
With the new update, will we still need to choose either "redux-simple-router" or "redux-router" for the react+react-router+redux combo?

**Comment by timdorr** [comment]
You should probably use redux-simple-router. But that's a separate project. We don't worry about specific implementations of bindings to other libraries. 

The current docs on master are updated for 2.0.0. Just follow the upgrade guide.

**Comment by timbur** [comment]
Sorry to go off topic a bit here, but I was unable to find anything about React v0.15's `context`after a quick search.  Where can I find that info/discussion?

**Comment by timdorr** [comment]
@timbur It's based on some internal rumblings from the React team at Facebook. If they're going to make any sort of changes, it will be on a deprecation schedule, of course.

**Comment by gaearon** [comment]
@timbur Not official but you the thread was here: https://twitter.com/sebmarkbage/status/628627030783868928

**Comment by ZuTa** [comment]
any timeline here ? What's left?

Is it OK to switch over to the latest RC? or API still might change?

**Comment by knowbody** [comment]
@ZuTa RC means no breaking changes, just bug fixes if any (see [this](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidate)).

**Comment by ZuTa** [comment]
@knowbody Thanks. Sorry for the noob question.

**Comment by vn38minhtran** [comment]
Please provide a document about how to write a middleware component.
If use multiple middleware, how to handle `createElement` when both middleware depend on it ([like](https://github.com/rackt/async-props/blob/master/modules/AsyncProps.js#L208)).

```js
const createElement = (Component, props) => {
  // How to handle Middleware1Container and Middleware2Container
};
...
ReactDOM.render(
    <Router routes={routes}
      history={history}
      createElement={createElement}
      render={props => (
        <Middleware1 {...props} render={props => (
          <Middleware2 {...props} render={props => (
            <RouterContext {...props}/>
          )}/>
        )}/>
      )}/>,
    document.getElementById('app')
  );
```

**Comment by DanielHeath** [comment]
So, at the moment the `match` function gives you `renderProps`, but doesn't actually tell you which route matched.

It'd be really useful to be able to introspect the matched route and navigate to its parents (e.g. I set an extra `title` attribute on the route and use that to set the `<title>` for server rendering).

It's super hacky, awkward code at the moment because there isn't really a nice way to (eg) inherit a default title.

**Comment by timdorr** [comment]
Keep in mind that a route is normally comprised of a nested set of routes. When we pass along `this.props.route` to a routed component, that's the route for that particular segment of the route tree that is active. The full array of routes is available on `renderProps.routes`. 

You can also get access to `renderProps.components` to get the list of components to be rendered (not their instances, just the classes). You can store static props on a component to access by the server. I do this to colocate data fetching functions alongside my components, which I resolve into my Redux state before rendering. You could do the same thing to store a `title` static property that you can use to fill in that part of your page template.

**Comment by DanielHeath** [comment]
Right - it works nicely from the component.

The awkwardness in this situation comes from the router only rendering the `<body>` of the page.

Being able to get the `routes` that matched from renderProps would mean not having to re-jig everything to give the router control of the full page.

**Comment by DanielHeath** [comment]
I could also use a static property (global variables, yay) - except that that's a race condition waiting to happen on the server.

**Comment by timdorr** [comment]
> Being able to get the routes that matched from renderProps would mean not having to re-jig everything to give the router control of the full page.

I think you mis-read. Those are available. They're at `renderProps.routes`.

**Comment by DanielHeath** [comment]
Ahh, I understand now. I was confused when inspecting it because the first one was the root route (so looked like a complete list of routes.

**Comment by vishaltelangre** [comment]
This issue's [description](#issue-120567126) has following:

```js
// v2.0.0
class RouteComponent extends React.Component {
  someHandler() {
    this.props.router.push(...)
  }
}
```

which should be:

```js
// v2.0.0
class RouteComponent extends React.Component {
  someHandler() {
    this.context.router.push(...)
  }
}
```
Also, [v2.0.0 Upgrade Guide](https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md) doesn't seem to have instructions given here in **Lifecycle Mixin with deep, non-route components** section. I will send a PR if needed for the same.

Beside, I am really happy to see this terrific work on v2.0. A big "Hi, Five!" to the React Router team.

**Comment by mikestopcontinues** [comment]
Hey all, not sure if this is the right place for a v2 bug, but with `react-router@2.0.0-rc5` and `history@2.0.0-rc2` (installed as a dep for react-router), both `browserHistory` and `hashHistory` are being exported as `undefined` from `/lib/index.js` and their respective js files.

```javascript
{ __esModule: true,
  // ...
  browserHistory: undefined,
  hashHistory: undefined,
  // ... 
}
```

**Comment by taion** [comment]
They are in fact exported properly – double check your setup.

**Comment by mikestopcontinues** [comment]
OK, can you offer a baseline to work from? I was using node 4.0.0 before, but I just tried upgraded to node 5.5.0, npm 3.5.3. I did a clean sweep in a new project, `npm cache clean && npm init -y && npm install --save react-router@2.0.0-rc5`, and the problem is the same.

**Comment by mmahalwy** [comment]
Any idea what should be done as a fix for scroll-behavior for the time being?

**Comment by timdorr** [comment]
@mjackson just pushed history 2.0.0-rc3 (Thanks, Michael! :metal:), so I think we're all good here. 

@ryanflorence Can you push out a 2.0.0-rc6 to suss out any final bugs? We can go 2.0.0 final soon afterwards :smile:

**Comment by timoxley** [comment]
You probably shouldn't publish prereleases or rcs as the `latest` tag on npm, especially when the docs & examples aren't yet ready.

**Comment by timdorr** [comment]
@timoxley That was fixed over here. It probably just needs to be applied to NPM as well.

**Comment by tleunen** [comment]
Testing the rc5 now and using the `hashHistory`, how are we supposed the disable the `queryKey`?

**Comment by timdorr** [comment]
@tleunen It's right in the upgrade guide: https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories

**Comment by coryhouse** [comment]
Is there a publicly viewable version of the full docs updated for 2.0 public yet? 

I'm aware of the 2.0 upgrade guide. Are that (and this thread) still the sole docs for 2.0?

**Comment by taion** [comment]
The docs on master are for 2.0.

**Comment by dagatsoin** [comment]
Coming from the redux-router-react discussion and switch to react-router 2.0 only for now. My 2 cts experience for the repo:  hard to be sure if the master is the V2. The npm version is confusing.

**Comment by timdorr** [comment]
Guess we can close this... :smile:
